name: Test Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.8' ]
    name: Test go-succinct-data-structure-trie Package
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      #- run: make test
      - run: go test -v
